name: ghapi
on: pull_request

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    ghapi:
        runs-on: ubuntu-latest
        steps:
            - name: install deps
              run: pip install ghapi

            - name: make a comment
              shell: python
              run: |
                  import os
                  from ghapi.core import GhApi
                  owner,repo = os.environ['REPO'].split('/')
                  api = GhApi(owner=owner, repo=repo)
                  api.issues.create_comment(os.environ['NUMBER'] ,'hello i am making a comment using `ghapi`')
              env:
                  NUMBER: ${{ github.event.number }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO: ${{ github.repository }}
