name: chatops
on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  wandb_trigger:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:
      - name: Get repo contents
        uses: actions/checkout@v3

      - name: Set up Python & install deps
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install ghapi wandb

      - name: Parse value from the command
        id: get-runid-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search('/wandb[\s+](\S+)', comment)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            if match:
              print(f'VAL_FOUND=true', file=f)
              print(f'RUN_ID={match.group(1)}', file=f)
            else:
              print(f'VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: Generate the comparison report
        if: steps.get-runid-value.outputs.VAL_FOUND == 'true'
        id: wandb-report
        run: python3 ./.github/scripts/wandb.py
        env:
          WANDB_ENTITY: coffee_pot
          WANDB_PROJECT: cicd-quickstart
          BASELINE_TAG: baseline
          RUN_ID: "${{ steps.get-runid-value.outputs.RUN_ID }}"
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Make a comment with the GitHub API
        uses: actions/github-script@v6
        if: steps.wandb-report.outcome == 'success'
        with:
          script: |
            var msg = `A comparison between the linked run and baseline is available [in this report](${process.env.REPORT_URL})`
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: msg
              });
        env:
          REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
