name: chatops
on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  wandb_trigger:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: pip install ghapi wandb

      - name: fetch baseline run
        id: baseline
        run: echo "pass"

      - name: get the run_id from comment
        shell: python
        run: |
          import os
          import re
          body = os.environ['github.event.comment.body']
          regex = r"/wandb (\S+)"
          matches = re.find(regex, body)
          print(matches[0])
          print(matches)
