name: using secrets in GH actions
on: [push]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show me the secrete
        run: echo  $MY_SUPER_SECRET
    env:
      MY_SUPER_SECRET: ${{secrets.MYSECRET}}
